node_js:
- "0.10"
language: node_js
env:
- COVERALLS_REPO_TOKEN="ckvmICpF1SAKEEXWuEr7zFuV34fKi01LR"
before_script:
- npm install -g istanbul
- npm install -g mocha
script: make test-cov
after_success:
- make coveralls
